### ISSUE TITLE
Adicionar referência à página de Níveis de Conhecimento

### ISSUE THREAD

**Issue by DanielsLuz** [unb-cjr/sap#2]
No index de Níveis de Conhecimento, seria interessante adicionar uma referência para alguma página que explica as definições dos níveis adotados por nós.

Adicionar referência à, por exemplo:
https://pt.wikipedia.org/wiki/Modelo_de_aquisi%C3%A7%C3%A3o_de_habilidades_de_Dreyfus

**Comment by rafaelalvescjr** [comment]
Adicionado!

https://github.com/unb-cjr/sap/commit/7a6778f180f7275ab51418165a5819ca09b9af47
