### ISSUE TITLE
Tabela de conhecimentos

### ISSUE THREAD

**Issue by DanielsLuz** [unb-cjr/sap#3]
#/knowledges
Organizar tabela:
Coluna "Descrição": Renomear para "Conhecimento"
Coluna "Nível": Atualmente está mostrando a "descrição" do nível. Mudar para
mostrar o próprio "Nível".

**Comment by rafaelalvescjr** [comment]
Corrigido!

https://github.com/unb-cjr/sap/commit/7a6778f180f7275ab51418165a5819ca09b9af47
