### ISSUE TITLE
Tabelas em geral

### ISSUE THREAD

**Issue by DanielsLuz** [unb-cjr/sap#9]
Muitas tabelas possuem a coluna "Código", seria melhor renomear para "Id"? O que
é "Código"? Código é usado pelo usuário? Acho que ID como identificador faz mais sentido.

Sugestão:
Renomar colunas "Código" presente em várias tabelas por "ID"

**Comment by rafaelalvescjr** [comment]
Removi a coluna "Código" das tabelas, não tem funcionalidade prática ao usuário.
